### ISSUE TITLE
pnpm install 报错问题：Error: Command failed: C:\WINDOWS\system32\cmd.exe /s /c "autoreconf -ivf" │ 'autoreconf' �����ڲ����ⲿ���Ҳ���ǿ����еĳ��� │ ���������ļ���

### ISSUE THREAD

**Issue by pingxiangren** [zhenyuWang/vue3-element-admin2#1]
git clone 项目到本地后，使用 vscode 打开项目文件夹，遵照 .md 教程使用 pnpm install 安装依赖，结果报错如下：

![npnm_error](https://user-images.githubusercontent.com/77879226/208870977-a8e5498e-f99f-49a3-a22e-7fded8c6c2d0.png)

尝试改用 npm ，实在太太太太慢（已经开了科学），放弃；改用 cnpm 依然报错（但不是同一个错误）；尝试将 node.js 版本改为 [从零到一：搭建一个Vue3开发框架](https://juejin.cn/post/7019625617943445512) 里的 14.16.1 版本，和最新版本报同样的错误。Bing 了好久不知道是哪出问题了。

**Comment by zhenyuWang** [comment]
测试mac正常，windows电脑复现该问题，参考[这篇文章](https://segmentfault.com/a/1190000040764846)的方案可以解决

**Comment by yyccyypsl** [comment]
请问解决了吗，我也遇到了这个问题

**Comment by zhenyuWang** [comment]
> 请问解决了吗，我也遇到了这个问题

上面已给出解决方案，如无法解决，请详细描述你的问题

**Comment by yyccyypsl** [comment]
<img width="606" alt="1673576616878" src="https://user-images.githubusercontent.com/122543229/212222536-4578c08b-ad4e-44cc-9fc8-a12a532d8ed3.png">
好像显示不能认证证书

**Comment by yyccyypsl** [comment]
和这个有点不一样

**Comment by yyccyypsl** [comment]
> > 请问解决了吗，我也遇到了这个问题
> 
> 上面已给出解决方案，如无法解决，请详细描述你的问题

请问能帮忙看一下吗

**Comment by zhenyuWang** [comment]
1. 是否开了梯子
2. 不要配置淘宝源试下
3. node版本降一下到 16 或 14
4. yarn 安装试下

**Comment by yyccyypsl** [comment]
> 1. 是否开了梯子
> 2. 不要配置淘宝源试下
> 3. node版本降一下到 16 或 14
> 4. yarn 安装试下



> 1. 是否开了梯子
> 2. 不要配置淘宝源试下
> 3. node版本降一下到 16 或 14
> 4. yarn 安装试下
开了梯子，yarn install报这个，我试着用pnpm install --ignore-scripts没报错，不知道是不是安装好了
<img width="602" alt="1673577375071" src="https://user-images.githubusercontent.com/122543229/212224202-9a76e39f-7ce7-4d8e-be0a-e97658afbe74.png">
